//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raymond.ADFS_MFA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Raymond.ADFS_MFA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        function DisableControl(controlId) {
        ///            document.getElementById(controlId).disabled = true;
        ///        }
        ///    &lt;/script&gt;
        ///&lt;div id=&quot;loginArea&quot;&gt;
        ///ERRORMSG
        /// &lt;form method=&quot;post&quot; id=&quot;loginForm&quot; &gt;
        /// &lt;input id=&quot;authMethod&quot; type=&quot;hidden&quot; name=&quot;AuthMethod&quot; value=&quot;%AuthMethod%&quot;/&gt;
        /// &lt;input id=&quot;context&quot; type=&quot;hidden&quot; name=&quot;Context&quot; value=&quot;%Context%&quot;/&gt;
        ///&lt;div id=&quot;titleDiv&quot; class=&quot;groupMargin&quot;&gt;
        ///	&lt;h1 id=&quot;sectionHeader&quot;&gt;Multifactor Authentication&lt;/h1&gt; 
        ///&lt;/div&gt; 
        /// PIC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthenticationForm_1033 {
            get {
                return ResourceManager.GetString("AuthenticationForm_1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        function DisableControl(controlId) {
        ///            document.getElementById(controlId).disabled = true;
        ///        }
        ///    &lt;/script&gt;
        ///
        ///&lt;div id=&quot;loginArea&quot;&gt;
        ///ERRORMSG
        /// &lt;form method=&quot;post&quot; id=&quot;loginForm&quot; &gt;
        /// &lt;input id=&quot;authMethod&quot; type=&quot;hidden&quot; name=&quot;AuthMethod&quot; value=&quot;%AuthMethod%&quot;/&gt;
        /// &lt;input id=&quot;context&quot; type=&quot;hidden&quot; name=&quot;Context&quot; value=&quot;%Context%&quot;/&gt;
        ///&lt;div id=&quot;titleDiv&quot; class=&quot;groupMargin&quot;&gt;
        ///	&lt;h1 id=&quot;sectionHeader&quot;&gt;Multi-Faktor Autentisering&lt;/h1&gt; 
        ///&lt;/div&gt; 
        /// P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthenticationForm_1044 {
            get {
                return ResourceManager.GetString("AuthenticationForm_1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Vennligst konfigurer din Autentiserings App (Microsoft Verificator, Google Authenticator, et al.) ved å bruke QR koden under.&lt;br/&gt;
        ///&lt;a href=&quot;https://uit.no/Oraklet/SomeWhere&quot;&gt;Les her for assistanse.&lt;/a&gt;&lt;/p&gt;
        ///&lt;br /&gt;
        ///&lt;img width=&quot;{0}&quot; height=&quot;{1}&quot; src=&quot;https://chart.googleapis.com/chart?chs={0}x{1}&amp;amp;chld=M%7C0&amp;amp;cht=qr&amp;amp;chl%3Dotpauth%3A%2F%2Ftotp%2FUiT%20MFA%3A({2})%3Fsecret%3D{3}&quot;&gt;
        ///&amp;issuer=ACME%20Co&amp;algorithm=SHA1&amp;digits=6&amp;period=30
        ///
        ///otpauth://totp/UiT Secure Logon ({0})?secret={1}&amp;issuer={2}&amp;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Backup22032017 {
            get {
                return ResourceManager.GetString("Backup22032017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA256.
        /// </summary>
        internal static string SecretAlgorithm {
            get {
                return ResourceManager.GetString("SecretAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string SecretDigits {
            get {
                return ResourceManager.GetString("SecretDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UiT Secure Login.
        /// </summary>
        internal static string SecretIssuer {
            get {
                return ResourceManager.GetString("SecretIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SecretName {
            get {
                return ResourceManager.GetString("SecretName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string SecretPeriode {
            get {
                return ResourceManager.GetString("SecretPeriode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Please configure your Google Authenticator App by using the QR code below.&lt;br/&gt;
        ///&lt;a href=&quot;https://uit.no/Oraklet/&quot;&gt;Read this for assistance.&lt;/a&gt;&lt;/p&gt;
        ///&lt;br /&gt;
        ///&lt;img width=&quot;{0}&quot; height=&quot;{1}&quot; src=&quot;https://chart.googleapis.com/chart?chs={0}x{1}&amp;chld=M|0&amp;cht=qr&amp;chl={2}&quot;&gt;.
        /// </summary>
        internal static string WebForm_1033 {
            get {
                return ResourceManager.GetString("WebForm_1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Vennligst konfigurer din Google Authenticator App ved å bruke QR koden under.&lt;br/&gt;
        ///&lt;a href=&quot;https://uit.no/Oraklet/&quot;&gt;Les her for assistanse.&lt;/a&gt;&lt;/p&gt;
        ///&lt;br /&gt;
        ///&lt;img width=&quot;{0}&quot; height=&quot;{1}&quot; src=&quot;https://chart.googleapis.com/chart?chs={0}x{1}&amp;chld=M|0&amp;cht=qr&amp;chl={2}&quot;&gt;.
        /// </summary>
        internal static string WebForm_1044 {
            get {
                return ResourceManager.GetString("WebForm_1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to otpauth://totp/{0}{1}?secret={2}&amp;issuer={3}.
        /// </summary>
        internal static string WebFormSecret {
            get {
                return ResourceManager.GetString("WebFormSecret", resourceCulture);
            }
        }
    }
}
